name: CI/CD Pipeline

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      VITE_ADMIN_EMAIL: ${{ secrets.VITE_ADMIN_EMAIL }}
      VITE_ADMIN_PASSWORD: ${{ secrets.VITE_ADMIN_PASSWORD }}
      VITE_ADMIN_ROLE: ${{ secrets.VITE_ADMIN_ROLE }}
      VITE_DESIGNER_EMAIL: ${{ secrets.VITE_DESIGNER_EMAIL }}
      VITE_DESIGNER_PASSWORD: ${{ secrets.VITE_DESIGNER_PASSWORD }}
      VITE_DESIGNER_ROLE: ${{ secrets.VITE_DESIGNER_ROLE }}
      VITE_APP_API_KEY: ${{ secrets.VITE_APP_API_KEY }}
      VITE_APP_AUTH_DOMAIN: ${{ secrets.VITE_APP_AUTH_DOMAIN }}
      VITE_APP_PROJECT_ID: ${{ secrets.VITE_APP_PROJECT_ID }}
      VITE_APP_STORAGE: ${{ secrets.VITE_APP_STORAGE }}
      VITE_APP_SENDER_ID: ${{ secrets.VITE_APP_SENDER_ID }}
      VITE_APP_APP_ID: ${{ secrets.VITE_APP_APP_ID }}
      VITE_APP_MESURE_ID: ${{ secrets.VITE_APP_MESURE_ID }}
      VITE_APP_CLOUDINARY_CLOUD_NAME: ${{ secrets.VITE_APP_CLOUDINARY_CLOUD_NAME }}
      VITE_APP_CLOUDINARY_API_KEY: ${{ secrets.VITE_APP_CLOUDINARY_API_KEY }}
      VITE_APP_CLOUDINARY_API_SECRET: ${{ secrets.VITE_APP_CLOUDINARY_API_SECRET }}
      VITE_APP_CLOUDINARY_UPLOAD_PRESET: ${{ secrets.VITE_APP_CLOUDINARY_UPLOAD_PRESET }}
    steps:
      - uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Install dependencies
        run: pnpm install

      - name: Run unit tests
        run: pnpm test:unit

      - name: Run integration tests
        run: pnpm test:integration

      - name: Run Cypress tests
        uses: cypress-io/github-action@v5
        with:
          start: pnpm dev
          wait-on: "http://localhost:3000"
          wait-on-timeout: 60

  deploy:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v3

      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
          channelId: live
